export default{
    
  "login": "anukm32",
  "id": 77185881,
  "node_id": "MDQ6VXNlcjc3MTg1ODgx",
  "avatar_url": "https://avatars.githubusercontent.com/u/77185881?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/anukm32",
  "html_url": "https://github.com/anukm32",
  "followers_url": "https://api.github.com/users/anukm32/followers",
  "following_url": "https://api.github.com/users/anukm32/following{/other_user}",
  "gists_url": "https://api.github.com/users/anukm32/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/anukm32/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/anukm32/subscriptions",
  "organizations_url": "https://api.github.com/users/anukm32/orgs",
  "repos_url": "https://api.github.com/users/anukm32/repos",
  "events_url": "https://api.github.com/users/anukm32/events{/privacy}",
  "received_events_url": "https://api.github.com/users/anukm32/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-01-09T06:03:59Z",
  "updated_at": "2021-08-05T14:37:28Z"

}